# 2 - Introduction to NumPy

## Textbook Part II. Chapters 4 and 5.


NumPy (__Numerical Python__) provides an efficient interface to store and operate on dense data buffers through __arrays__.

In some ways, NumPy arrays work like Python's built-in `lists`. However, NumPy arrays provide much more efficient operations, especially for large volumes of data.

NumPy arrays form the core of the entire data science and machine learning ecosystem.


To install NumPy using `pip`:

In [ ]:
%pip install numpy

To start using NumPy, we will use the `import` directive, and we will assign to NumPy the alias `np` to make it easier to refer to it in the code.

In [1]:
import numpy as np

Now we can use NumPy using the `np` alias. The following line displays NumPy's built-in documentation using the `?` operator.

In [2]:
np?

Type:        module
String form: <module 'numpy' from '/Users/mgouveag/Sync/Courses/CSC 8000/Lecture Notebooks/.venv/lib/python3.13/site-packages/numpy/__init__.py'>
File:        ~/Sync/Courses/CSC 8000/Lecture Notebooks/.venv/lib/python3.13/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Co

## More on Python data types

Python is implemented in C. This means every Python object is a C structure, containing not only the object's value but other information as well.

An integer is Python, such as `x=1000` stores not only the integer value, but also a compound C structure.

This means that an integer in Python has a memory overhead not present in lower-level languages such as C.

A similar reasoning can be applied to Python's `list`. The standard `list` in Python is dynamic-typed, meaning it is capable of storing objects of different types (integers, strings, other lists, etc.). This also incurs a memory overhead that is not necessary when all objects are of the same type.


### Fixed-type arrays in Python

Python offers a built-in `array` module (since Python 3.3) that can be used to create dense arrays of a single type:

In [3]:
import array

L = list(range(10))  # Create a list of values
A = array.array('i', L)  # Create an array of integers ('i') using the elements in L
print(A)


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Fixed-type arrays using NumPy

While Python's `array` provides an efficient interface to handle vector data, NumPy's `ndarray` object provides much more functionality to them, such as array arithmetic, filtering, broadcasting, and more. For that reason, we will focus on `ndarray` instead of the built-in `array` objects.

### Creating arrays from Python lists

In [5]:
import numpy as np

np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

The above code infers that the data type to be used for the array is __integer__.

We can enforce a particular data type using the `dtype` parameter:

In [ ]:
np.array([1, 4, 2, 5, 3], dtype=np.float32)

This creates an array of 32-bit precision floating-point values.

_Nested lists_ are converted into 2D NumPy arrays:

In [6]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating arrays from scratch

NumPy has a number of routines to help creating arrays from scratch. Here are a few examples:

In [7]:
## Create an array of 10 integer elements filled with 0s

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
## Create a 3x5 array filled with 1s

np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
## Create a 3x5 array filled with the value 3.14

np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
## Create an array filled with a sequence starting a 0, ending at 20, stepping by 2

np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
## Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
## Create an identity matrix of dimensions 4x4.

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
## Create an array of 20 integers initialized with garbage values (empty).

np.empty(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### NumPy standard data types

Remember: NumPy arrays contain values of a _single type_. Some of the common types we will use are:

- `np.int64` - 64-bit integer
- `np.int32` - 32-bit integer
- `np.int16` - 16-bit integer
- `np.float64` - 64-bit floating point
- `np.float32` - 32-bit float
- `np.float16` - 16-bit float

## The basics of NumPy arrays

Next, we will cover some of the basic array manipulation concepts:

- Array attributes
- Indexing arrays
- Array slicing
- Array reshaping
- Array joining and splitting

### Array attributes

To illustrate array attributes, we will define 3 randomly generated arrays using NumPy's random utility:

In [22]:
import numpy as np

rng = np.random.default_rng(seed=1701)  # define a random number generator

x1 = rng.integers(10, size=6)  # integers up to 10
x2 = rng.integers(10, size=(3 ,4))  # 2d array
x3 = rng.integers(10, size=(3, 4, 5))  # 3d array

In [23]:
print(x1)
print(x2)
print(x3)

[9 4 0 3 8 6]
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


Each of the above arrays has attributes including `ndim`, `shape`, `size` and `dtype`. Let's take a look at them:

In [24]:
print(f"x3 ndim: {x3.ndim}")
print(f"x3 shape: {x3.shape}")
print(f"x3 size: {x3.size}")
print(f"dtype: {x3.dtype}")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64


__Quiz__ - What will be the output of each of the following?

1. `x1.ndim`
2. `x2.size`
3. `x1.shape`

### Array Indexing

Array indexing works in a very similar fashion to Python lists. In a one-dimensional array, index `i` corresponds to the i-th element of the array, counting from zero.

In [25]:
print(x1[0])
print(x1[4])

9
8


Use negative indices to index from the end of the array:

In [26]:
print(x1[-1])
print(x1[-2])

6
8


In a __multidimensional array__, items can be accessed using a comma-separated `(row, column)` tuple:

In [27]:
print(x2[0, 0])  # Get the element in the first row and first column
print(x2[2, 0])  # Get the element n row 2, first column
print(x2[2, -1])

3
0
9


__Modifying__: values can be changed using the index notation:

In [28]:
x2[0, 0] = 12
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


### Array slicing

Slicing of NumPy arrays are similar to the slicing of Python lists. The basic syntax is `x[start:end:step]`.

#### Slicing one-dimensional arrays

In [29]:
print(x1)

[9 4 0 3 8 6]


In [30]:
print(x1[:3])  # Get the first three elements

[9 4 0]


In [31]:
print(x1[1:4])  # Get element indices 1 through 3

[4 0 3]


In [33]:
print(x1[::2])  # Get every second element

[9 0 8]


When `step` is _negative_, the slicing moves backward. We can use this to easily reverse an array:

In [34]:
print(x1)
print(x1[::-1])  # All elements, reversed

[9 4 0 3 8 6]
[6 8 3 0 4 9]


#### Slicing multidimensional arrays

To slice multidimensional arrays, we use slices separated by commas:

In [35]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [36]:
print(x2[:2, :3])  # First two rows and first three columns

[[12  1  3]
 [ 4  0  2]]


In [37]:
print(x2[:3, ::2])  # first three rows, every second column

[[12  3]
 [ 4  2]
 [ 0  6]]


In [38]:
print(x2[::-1, ::-1])  # All rows and columns, reversed

[[ 9  6  0  0]
 [ 3  2  0  4]
 [ 7  3  1 12]]


We can use slicing combined with indexing to access a single row or column of a multidimensional array:

In [39]:
print(x2[: ,0])  # Get the first column of x2

[12  4  0]


In [40]:
print(x2[2, :])  # Get the third row of x2
print(x2[2])

[0 0 6 9]
[0 0 6 9]


#### Slices are no-copy views

NumPy array slices are _views_ of the original array, rather than _copies_ of data. This means any changes to the slices __also affect the original array__. 
Consider the following:

In [41]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [42]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


Let us modify `x2_sub` and see what happens to `x2`:

In [43]:
x2_sub[0, 0] = 99
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


#### Creating copies of arrays

Using views can be an efficient way of accessing sub arrays. However, you might want to create a real copy of the array after slicing. To do that, you can use the `copy` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

Changes made to `x2_sub_copy` will __not be reflected upon `x2`__.

### Reshaping arrays

Array reshaping can be used to change the shape of your array, such as turning a 1D array into a 2D one. This is done using the `reshape` method. For example, assume you want to put the numbers 1 through 9 in a `3 x 3` grid:

In [44]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
grid.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
grid.reshape(1,9).T.shape

(9, 1)

Note that the initial array size __must match the size of the reshaped array__.

### Array concatenation and splitting

NumPy provides tools to combine arrays into one, or split arrays into many.

#### Array concatenation

Joining two arrays in NumPy can be accomplished in many ways, using: `np.concatenate`, `np.vstack`, `np.hstack`.

`np.concatenate` takes a tuple or a list of arrays and produces a single array that concatenates them:

In [55]:
x = np.array([1,2,3])
y = np.array([3,2,1])

print(np.concatenate([x, y]))  # concatenate arrays x and y

[1 2 3 3 2 1]


You can concatenate multiple arrays at once:

In [56]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


For working with arrays of mixed dimensions, you can use `np.vstack` to stack arrays vertically, or `np.hstack` to stack arrays horizontally:

In [57]:
grid = np.array([[1,2,3], 
                 [4,5,6]])  # create a 2D array

In [58]:
# Stack grid and array x vertically

print(np.vstack([x, grid]))

[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [60]:
# Stack grid and y horizontally

y = np.array([[99], [99]])
print(np.hstack((grid, y)))

[[ 1  2  3 99]
 [ 4  5  6 99]]


#### Array splitting

To split an array, you can use function `np.split(a, indices)`. Where `a` is an input array, and `indices` is a list of indices where to split. For example:

In [61]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


The above example splits array `x` at indices 3 and 5, produces __three__ sub arrays as output.

Similarly, you can split arrays horizontally or vertically with `np.hsplit` and `np.vsplit`, respectively:

In [62]:
grid = np.arange(16).reshape((4,4))

upper, lower = np.vsplit(grid, [2])

print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [63]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Testing the performance of NumPy

Let us compare the running time of two programs that create very long lists/arrays.
The first uses a Python `list`, the second uses NumPy's `arange`.

In [64]:
%%timeit
l = []
for i in range(1000000):
    l.append(i)

18.7 ms ± 326 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%%timeit
x = np.arange(1000000)

487 μs ± 2.46 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
